# Generated by Django 5.2 on 2025-05-07 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Mangas',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mes_bds.author')),
            ],
            options={
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mes_bds.author')),
            ],
            options={
                'verbose_name_plural': 'Bandes dessinees',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL, verbose_name='Membre de la famille')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_maker', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name_plural': 'Membres de la famille',
                'constraints': [models.UniqueConstraint(fields=('user', 'family_member'), name='unique_user_user'), models.CheckConstraint(condition=models.Q(('user', models.F('family_member')), _negated=True), name='user_not_equal_to_family_member')],
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mes_bds.book', verbose_name='Livre')),
                ('comic_book_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_book', to='mes_bds.comicbook', verbose_name='Bande dessinee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL, verbose_name='Proprietaire')),
                ('manga_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='mes_bds.manga', verbose_name='Manga')),
            ],
            options={
                'verbose_name_plural': 'Bibliothèques',
                'constraints': [models.UniqueConstraint(fields=('user', 'comic_book_list'), name='unique_user_comic'), models.UniqueConstraint(fields=('user', 'manga_list'), name='unique_user_manga'), models.UniqueConstraint(fields=('user', 'book_list'), name='unique_user_book')],
            },
        ),
    ]
