# Generated by Django 5.2 on 2025-08-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mes_bds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='title',
            new_name='name',
        ),
    ]
