# Generated by Django 5.2 on 2025-08-30 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes_bds', '0002_rename_title_serie_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='library',
            name='unique_user_book',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='book_list',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='mes_bds.artist', verbose_name='Artiste'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID de couverture'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book'),
        ),
    ]
