# Generated by Django 5.2 on 2025-08-30 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes_bds', '0003_remove_library_unique_user_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN_10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ISBN_13',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ISBN'),
        ),
    ]
