# Generated by Django 5.2 on 2025-08-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes_bds', '0004_remove_book_isbn_10_remove_book_isbn_13_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titre'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('serie', 'number'), name='unique_serie_number'),
        ),
    ]
