# Generated by Django 5.2.6 on 2025-09-11 10:21

from django.db import migrations


def create_unsorted_serie(apps, schema_editor):
    Serie = apps.get_model('my_library', 'Serie')
    Serie.objects.create(
        name='Unsorted',
        description='Serie for new add books'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('my_library', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_unsorted_serie)
    ]
