# Generated by Django 5.2.6 on 2025-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('my_library', '0002_auto_20250911_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='books', to='my_library.author',
                                         verbose_name='Auteurs'),
        ),
    ]
