# Generated by Django 5.2.6 on 2025-09-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0003_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
