# Generated by Django 5.2.6 on 2025-09-11 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0004_rename_author_book_authors'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique_serie_number',
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ISBN'),
        ),
    ]
