# Generated by Django 5.2.6 on 2025-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0005_remove_book_unique_serie_number_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_ID',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover/', verbose_name='Couverture'),
        ),
    ]
