# Generated by Django 5.2.6 on 2025-09-17 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0006_remove_book_cover_id_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_publish_year',
            field=models.SmallIntegerField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Première publication'),
        ),
    ]
