# Generated by Django 5.2.6 on 2025-09-17 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0007_book_first_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_publish_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Première publication'),
        ),
    ]
