# Generated by Django 5.2.6 on 2025-09-24 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0008_alter_book_isbn_alter_book_first_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='first_publish_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)], verbose_name='Première publication'),
        ),
    ]
