# Generated by Django 5.2 on 2025-08-27 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 10, 30, 23, 711037, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
        ),
    ]
