# Generated by Django 5.2 on 2025-08-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
