name: Déploiement automatique sur Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Ajouter la clé SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Déployer sur le serveur
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.SERVER_DIRECTORY }} &&
            git pull origin main &&
            ~/.local/bin/poetry install &&
            source .venv/bin/activate &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput --clear &&
            sudo systemctl restart gunicorn
          "
