name: Déploiement automatique sur Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Ajouter la clé SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Déployer sur le serveur
        run: |
          ssh -o StrictHostKeyChecking=no spleen@176.151.222.148 "
            cd /home/spleen/BD &&
            git pull origin main &&
            source .venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            sudo systemctl restart gunicorn
          "
